version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: looper # Nom de la base de données
      MYSQL_USER: my_user         # Nom de l'utilisateur
      MYSQL_PASSWORD: my_password # Mot de passe de l'utilisateur
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

volumes:
  dbdata: